spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 197546
    url: jdbc:mysql://1.94.1.34:3306/QianFen
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 6000



# 整合mybatis-plus
mybatis-plus:
  #如果mapper映射文件与mapper接口不在同一级那么需要进行制定
#  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zx.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


